
title: Observium Community Edition as Docker container
description: Build the Project Documentation
show_downloads: true
google_analytics: UA-174405517-1
url: "http://github.code-snipes.de/docker-observium"
theme: jekyll-theme-modernist
maintinance: true

github:
  owner_name: "Patrick Hayo"
  zip_url: https://github.com/adminph-de/docker-observium/download.zip
  tar_url: https://github.com/adminph-de/docker-observium/download.tar
  repository_url: https://github.com/adminph-de/docker-observium
